"""auto generate book_borrow table

Revision ID: 0d0ec2cf2c4c
Revises: 2e2c34db1cf5
Create Date: 2022-02-20 22:46:41.340750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0ec2cf2c4c'
down_revision = '2e2c34db1cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_borrow',
    sa.Column('book_borrow_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_transaction_id'], ['book_transaction.book_transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_borrow_id')
    )
    op.create_index(op.f('ix_book_borrow_book_borrow_id'), 'book_borrow', ['book_borrow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_borrow_book_borrow_id'), table_name='book_borrow')
    op.drop_table('book_borrow')
    # ### end Alembic commands ###
