"""auto generate ratings table

Revision ID: 12542ae067f9
Revises: f90501c16f82
Create Date: 2022-02-22 10:41:06.344168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12542ae067f9'
down_revision = 'f90501c16f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('given_by', sa.Integer(), nullable=False),
    sa.Column('given_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['given_by'], ['user_profile.user_profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index(op.f('ix_rating_rating_id'), 'rating', ['rating_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_rating_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
