"""auto generate status_id in book_transaction

Revision ID: 1c3f75b5b7da
Revises: bd041a3c19e0
Create Date: 2022-02-23 17:01:16.317796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3f75b5b7da'
down_revision = 'bd041a3c19e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_borrow', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book_borrow', 'status_code', ['status_id'], ['status_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_borrow', type_='foreignkey')
    op.drop_column('book_borrow', 'status_id')
    # ### end Alembic commands ###
