"""auto generate book_transaction table

Revision ID: 2e2c34db1cf5
Revises: 856336fb4dfc
Create Date: 2022-02-19 21:11:52.730614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2c34db1cf5'
down_revision = '856336fb4dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_transaction',
    sa.Column('book_transaction_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_by', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW() + INTERVAL '5 day'"), nullable=True),
    sa.Column('book_fine', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrowed_by'], ['user_profile.user_profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_transaction_id')
    )
    op.create_index(op.f('ix_book_transaction_book_transaction_id'), 'book_transaction', ['book_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_transaction_book_transaction_id'), table_name='book_transaction')
    op.drop_table('book_transaction')
    # ### end Alembic commands ###
