"""auto generate book table

Revision ID: 856336fb4dfc
Revises: d20db9734ff3
Create Date: 2022-02-18 07:09:16.566031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856336fb4dfc'
down_revision = 'd20db9734ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('book_author', sa.String(), nullable=False),
    sa.Column('edition', sa.Integer(), nullable=False),
    sa.Column('book_category_id', sa.Integer(), nullable=False),
    sa.Column('book_price', sa.Float(), nullable=False),
    sa.Column('book_count', sa.Integer(), nullable=False),
    sa.Column('book_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_category_id'], ['book_category.book_category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_book_book_id'), 'book', ['book_id'], unique=False)
    op.create_unique_constraint(None, 'user_login', ['email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_login', type_='unique')
    op.drop_index(op.f('ix_book_book_id'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
