"""move role type to userlogin table

Revision ID: 91236e6a87d4
Revises: 0d0ec2cf2c4c
Create Date: 2022-02-21 00:52:41.784460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91236e6a87d4'
down_revision = '0d0ec2cf2c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_login', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.drop_constraint('user_profile_role_id_fkey', 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_profile_role_id_fkey', 'user_profile', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_login', type_='foreignkey')
    op.drop_column('user_login', 'role_id')
    # ### end Alembic commands ###
