"""fix: auto generate status_id in book_transaction

Revision ID: bb68f11aa84b
Revises: 1c3f75b5b7da
Create Date: 2022-02-23 17:08:22.315465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb68f11aa84b'
down_revision = '1c3f75b5b7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_borrow_status_id_fkey', 'book_borrow', type_='foreignkey')
    op.drop_column('book_borrow', 'status_id')
    op.add_column('book_transaction', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book_transaction', 'status_code', ['status_id'], ['status_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_transaction', type_='foreignkey')
    op.drop_column('book_transaction', 'status_id')
    op.add_column('book_borrow', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('book_borrow_status_id_fkey', 'book_borrow', 'status_code', ['status_id'], ['status_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
