"""auto generate status code table

Revision ID: bd041a3c19e0
Revises: d4ea4b372ca3
Create Date: 2022-02-23 00:23:42.944195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd041a3c19e0'
down_revision = 'd4ea4b372ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_code',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_status_code_status_id'), 'status_code', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_code_status_id'), table_name='status_code')
    op.drop_table('status_code')
    # ### end Alembic commands ###
