"""auto generate book_category table

Revision ID: d20db9734ff3
Revises: 1be4e7eba80d
Create Date: 2022-02-18 06:52:39.753772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20db9734ff3'
down_revision = '1be4e7eba80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('book_category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('book_category_id')
    )
    op.create_index(op.f('ix_book_category_book_category_id'), 'book_category', ['book_category_id'], unique=False)
    op.create_index(op.f('ix_book_category_category_name'), 'book_category', ['category_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_category_category_name'), table_name='book_category')
    op.drop_index(op.f('ix_book_category_book_category_id'), table_name='book_category')
    op.drop_table('book_category')
    # ### end Alembic commands ###
